gateways:
    local:
        connection:
            type: postgres
            host: localhost
            user: gitpod
            password: postgres
            port: 5432
            database: postgres

default_gateway: local

model_defaults:
    dialect: postgres
