dbt_playground:
  target: dbtdev
  outputs:
    dbtdev:
      type: postgres
      host: localhost
      user: gitpod
      password: postgres
      port: 5432
      dbname: postgres
      schema: dev_dbt_playground
      threads: 3
    dbtprd:
      type: postgres
      host: localhost
      user: gitpod
      password: postgres
      port: 5432
      dbname: postgres
      schema: prd_dbt_playground
      threads: 3